### PR TITLE
Add library interface to scrape multiple articles from domain url

### PR DESCRIPTION
**Pull request by mrknight21**

### CODE REVIEW

**Comment by fhamborg** [comment]
Hi, thanks for the PR! This is a really interesting one - I'm not 100% sure yet though how to proceed. Methodologically, I'm wondering what is the use case to crawl a complete website, which often takes a significant amount of time. Rather than having one command, i.e., `from_domain_url` with no feedback whatsoever, running for hours or potentially even days, I think for the use case of crawling a full website, the CLI mode should be preferred. What do you think is a proper use case here and why not use the CLI mode?

Technically, I'm wondering whether the heuristic that is used to decide whether the process should wait for more articles or is "finished" is sophisticated enough, e.g., https://github.com/mrknight21/news-please/blob/42656822b7af48ffba77e1955ca8519285700fba/newsplease/__init__.py#L154 checks whether new articles have been downloaded since 5 seconds ago. While this will probably work usually, it often will not, e.g., some news outlets will temporarily pause or even block http request sent by news-please, if too many requests were performed in a specific time. So, I think the decision whether crawling is finished or should be continued cannot be only based on this factor.

**Comment by mrknight21** [comment]
Hi Felix! Thanks for the feedback. New Please is a wonderful tool. I really appreciate your effort in this. And sorry that I just replied to you now. I agree with most of your points that normally if someone want to scrape a full website using the CLI will be the more appropriate approach. And I admit that domain_url heuristic check is not sophiscated enough. A better approach is probably to check the thread finished or not. But I guess the thread will never finish because of "the stop_after_job" has been turned off (If I understand correctly?). 

Now rethinkng about my own requirment and scenario, I guess what I am looking for is to make the SingleCrawler customizable outside the config files, especially in library mode.There are two difficulties that I have observed. 1. The Single Crawler class only read attribute from the config files. 2. The start of the crawling process is inside the construction function. If we allow json as alternatives for some of the config file address string, will it be more flexible? And if we separate the start of the crawling process away from the constructor, will it give user more space to implement logic between the initiation of the crawler and the start of the crawling. One use case scenario is integrating the news please with an event based distributed system, where many workers/processer are deployed, and the configs are contained in the events as json object. And the processor take the json format object and scrape accordingly. Thanks

**Comment by fhamborg** [comment]
Thanks for reply. Given that the motivation leading to your changes seems to have changed on your side, I'd like to suggest that you open another PR for what you described now and I'm going to close this PR. 

Even though, as said, while I'm not 100% sure regarding the use cases of such changes, I do like the idea of full website crawling from library mode. So, I would even be willing to merge this PR (147), given it has a more reliable termination condition (as discussed above). Regarding that, I don't exactly know what you mean when referring to 
> But I guess the thread will never finish because of "the stop_after_job" has been turned off (If I understand correctly?).

Could you elaborate on that?

**Comment by fhamborg** [comment]
It seems at least some of recent changes, esp. the analyzer, are unrelated to this PR. Closing the PR, thus, but feel free to contact me should you still plan on adding such functionality as was described in the PR.

**Pull request closed without merging**
