### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by ntlf**
Added Dockerfile and a script that starts the crawler.

### CODE REVIEW

**Comment by ntlf** [comment]
An automated docker build would be great on hub.docker.com, but it's up to you @fhamborg.

If it's done then the readme should contain some reference to it.
```
docker run -d -v <config>:/news-please/newsplease/config/ <your-docker-name>/news-please
```

**Comment by fhamborg** [comment]
yea, thats a good idea, but im wondering if the start script can be improved, because currently it would start crawling articles from the example articles. what do you think?

thanks for your pull request! :-)

**Comment by ntlf** [comment]
That's while it should mount a folder when the docker starts. 
`-v <config>:/news-please/newsplease/config/`

You can place your own `config.cfg` and `sitelist.hjson` into that <config> folder, and it will be loaded by the crawler.

**Comment by fhamborg** [comment]
i havent used docker before, beside adding this information to the readme, is there anything to do (changes in the code, etc)?

**Comment by ntlf** [comment]
No, it's working well without any changes in the codebase. :)

But a docker build would be necessary to provide an image. 
- https://hub.docker.com/
- login or create an account
- Create / Create Automated Build / Github / Select the project, and the default settings are fine
- On the dashboard, select the project, navigate to the Build Settings tab, and trigger a build. You have to do this now, because there are no new commits in the repo.

**Comment by sakinho** [comment]
This is great! I'm just missing the info on the readme or the wiki to enjoy all the power of news-please dockerized. Thanks!

**Comment by fhamborg** [comment]
Okay, the docker is created now. https://hub.docker.com/r/fhamborg/news-please/ Thanks @ntlf for your help!

**Comment by fhamborg** [comment]
@sakinho I'm not really familiar with docker yet, what info would be helpful to you in the readme?

**Comment by sakinho** [comment]
I think it would be useful to know that docker version exists and the commands to create the image and the commands to execute news-please.

Also I think is key in documentation (in general) a way to execute news-please all the time, everyday, in order to get a lot of news. I have red we can demonize RSS Crawler, but it would be nice to demonize all news please or at least execute ir several times a day easily.

**Comment by fhamborg** [comment]
Currently, I neither have the time available to add that nor do we need the docker image in our group. However, if you'd like to contribute, I'd be very happy to merge a pull request that adds this info to the readme and/or provides additional functionality so that the dockerized news-please works out of the box for the use cases you mentioned.

**Pull request merged**
