### PR TITLE
Commoncrawl crawler: use system temp file in a writable folder

### PR DESCRIPTION
**Pull request by lgov**
Make the commoncrawl crawler when running in a docker container. Use a temp file opened by the system, not the hard-coded file .tmpaws.txt in the src directory that probably not writable.

### CODE REVIEW

**Comment by lgov** [comment]
Hm, I see that multiple changes were included in this pull request, I'll update it with only 871a505.

**Comment by fhamborg** [comment]
Hi @lgov thanks for your PR. I would love to merge, but the PR currently still contains multiple other changes. I will close this PR - could you open a new one only containing the "use system temp file in a writable folder"? Thank you :)

**Comment by lgov** [comment]
FYI: there is a merge conflict with these changes and pending pull request #184, so if you plan to merge that one I'll wait before I prepare this pull request again.

**Comment by fhamborg** [comment]
alright, thanks :) i already merged 184

**Pull request closed without merging**
