### PR TITLE
Add the possibility to define a schema for postgresql database

### PR DESCRIPTION
**Pull request by yldoctrine**
Hello, thank you for your work on news-please.

Here is a pull request to add the possibility of using a schema in a postgresql database. I would need this improvement so the news-please tables don't live in the public schema.

I'll gladly make any change if you think something should be updated.

Thanks for your time

### CODE REVIEW

**Comment by fhamborg** [comment]
A few of the early contributors of NP contributed all DB-related functionality, so this one catches me off guard kind of ;o) Could you let me know, how the PR will change using NP? Also some more detailed background regarding what the current issue is and how the PR exactly fixes it would be helpful. Thank you!

**Comment by yldoctrine** [comment]
Thanks for your reply !
This PR introduces an optional schema for Postgres database. In practice nothing changes if you don't specify the schema in the configuration (default behaviour). If you specify the schema, NP will interact with the tables on the corresponding schema.
The issue I have, is that NP's tables `CurrentVersions` and `ArchiveVersions` currently live in Postgres public schema with other unrelated tables (my tables, other libraries tables). I'd prefer to have them live in a separate schema dedicated to NP, so that there is no confusion of their usage. I would also be able to use `CurrentVersions` and `ArchiveVersions` table names for other purpose in the public schema.
Thank you

**Comment by yldoctrine** [comment]
Yes, exactly

**Review by fhamborg — APPROVED** [review]

**Comment by fhamborg** [comment]
I'm currently not in office but will upload a new pypi version once I'm back. Thanks for the PR!

**Comment by yldoctrine** [comment]
Thank you

**Pull request merged**
