### PR TITLE
Pass optional arguments to requests.get

### PR DESCRIPTION
**Pull request by jkawamoto**
It would be beneficial if users could pass optional arguments, such as authentication information and proxy configurations, to requests made by `NewsPlease.from_url` and `NewsPlease.from_urls`.

This PR adds `**kwargs` to the above functions and passes them to `requests.get` in `SimpleCrawler._fetch_url`.

With this change, users can add authentication information like this:

```python
from newsplease import NewsPlease
from requests.auth import HTTPBasicAuth

NewsPlease.from_url("https://example.com", auth=HTTPBasicAuth("user", "password"))
```

and also add proxy configurations like this:

```python
from newsplease import NewsPlease

proxies = {
    "http": "http://10.10.1.10:3128",
    "https": "http://10.10.1.10:1080",
}

NewsPlease.from_url("https://example.com", proxies=proxies)
```

Related to #234 and https://github.com/fhamborg/news-please/discussions/254.

### CODE REVIEW

**Comment by fhamborg** [comment]
Hi! Thanks for the suggestion. Sounds like an interesting extension, though I think it would be more future-proof if we add a kwargs parameter specifically for requests. For example:

```
from newsplease import NewsPlease

request_args = {
    "proxies": {
           "http": "http://10.10.1.10:3128",
           "https": "http://10.10.1.10:1080",
      }
}

NewsPlease.from_url("https://example.com", request_args=request_args
```

This way, if at any point in the future we want to expose / forward arguments to / of other libraries used by NP, we could easily do so using the above.

**Comment by jkawamoto** [comment]
Thank you for your review. I added a commit so that the fetch functions now use `request_args` instead of `**kwargs`.

**Comment by fhamborg** [comment]
Thanks a lot for the changes. I'll have to think about what to do with the other two parameters of request that are directly exposed (timeout and user_agent). Currently have a tendency towards removing them to have a clean interface. I'll get back to you soon regarding this.

**Comment by fhamborg** [comment]
For cleaner consistency of the changes introduced by the PR, could you remove timeout and user_agent from the method signature as they would be set through the new parameter the PR introduces?

**Review by fhamborg — CHANGES_REQUESTED** [review]
see previous comment

**Comment by jkawamoto** [comment]
I've just added a commit to remove `timeout` and `user_agent`.  These parameters can now be passed via `request_args`.

**Pull request merged**
