### PR TITLE
Add Github Actions build

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

https://github.com/gliptak/news-please/runs/2512956742

### CODE REVIEW

**Comment by fhamborg** [comment]
Hi, what is this PR about?

**Comment by gliptak** [comment]
@fhamborg adds a build building PRs/master and putting a checkmark indicating status as can be seen at https://github.com/gliptak/news-please/pulls

**Comment by fhamborg** [comment]
I'm sorry, I don't know about that. What's the objective and benefits of this?

**Comment by gliptak** [comment]
Background info at https://github.com/features/actions

**Comment by fhamborg** [comment]
I am aware of Github Action and their intent. But your PR and comments still do not convey any information what the intended  benefit of this PR is for the news-please project. Feel free to reopen, providing a specific explanation. Thanks

**Pull request closed without merging**
