### PR TITLE
fixes #172 and #169: NewsPlease.from_urls() - use multiprocessing

### LINKED ISSUE #172: NewsPlease.from_urls() could use multiprocessing
**Mandatory**
* [x] I read the documentation ([readme](https://github.com/fhamborg/news-please/blob/master/README.md) and [wiki](https://github.com/fhamborg/news-please/wiki)).
* [x] I searched other issues (including closed issues) and could not find any to be related. If you find related issues post them below or directly add your issue to the most related one.

**Describe the bug**

In a few runs with added debugging, I observed that the html extraction step takes a good chunk of time for completion, while the downloading part (already threaded) not so much.

**To Reproduce**

Add this to `newsplease/__init__.py::NewsPlease.from_urls()`, around where it calls `.from_html()` for each url scraped:

```py
tic = time.time()
for url in results:
    results[url] = NewsPlease.from_html(results[url], url, download_date)
toc = time.time()
print(f"Extracted from HTML: {(toc - tic):.2f} seconds")
```

and this to `newsplease/crawler/simple_crawler.py::SimpleCrawler.fetch_urls()` around where it calls threads to download articles:

```py
tic = time.time()
threads = [threading.Thread(target=SimpleCrawler._fetch_url, args=(url, True, timeout)) for url in urls]
for thread in threads:
    thread.start()
for thread in threads:
    thread.join()
toc = time.time()
print(f"Downloaded: {(toc - tic):.2f} seconds")
```

**Expected behavior**
Should not just attempt to use single core for a CPU intensive task

**Log**

- Before: 

```
Downloaded: 2.83 seconds
Extracted from HTML: 28.92 seconds
Step 1: Processed 120 articles. Took 31.77 seconds. 12378 articles remaining. ETA: 54.61 minutes
Downloaded: 4.09 seconds
Extracted from HTML: 25.89 seconds
Step 2: Processed 120 articles. Took 29.99 seconds. 12258 articles remaining. ETA: 52.57 minutes
```

Screenshot from 2020-08-03 11-22-56

- After https://github.com/fhamborg/news-please/pull/173:

```
Downloaded: 1.78 seconds
Extracted from HTML: 9.45 seconds
Step 1: Processed 120 articles. Took 11.24 seconds. 12378 articles remaining. ETA: 19.32 minutes
Downloaded: 1.93 seconds
Extracted from HTML: 12.08 seconds
Step 2: Processed 120 articles. Took 14.02 seconds. 12258 articles remaining. ETA: 21.50 minutes
Downloaded: 2.36 seconds
Extracted from HTML: 12.34 seconds
Step 3: Processed 120 articles. Took 14.72 seconds. 12138 articles remaining. ETA: 22.47 minutes
encoding error: utf-8 / UTF-8
Downloaded: 4.77 seconds
Extracted from HTML: 11.05 seconds
Step 4: Processed 120 articles. Took 15.83 seconds. 12018 articles remaining. ETA: 23.29 minutes
```
i.e. - More than 2x improvement in extraction time (of course, depending on the number of processors available)

Screenshot from 2020-08-03 11-28-22

**Versions (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS
 - Python Version: 3.6.9
 - news-please Version: `commit c79e8c35950dbfd30e1d5f4f3d291d97de488bad (HEAD -> master, origin/master, origin/HEAD)`

### PR DESCRIPTION
**Pull request by arcolife**
also, do not attempt to extract info from empty html responses

Return empty `{}` in case any errors encountered while extracting

### CODE REVIEW

**Comment by arcolife** [comment]
> removing the "inlined" for loop

Sure. Dict comprehensions (I heard comps are more pythonic, so..) are [only a couple seconds faster](https://stackoverflow.com/a/52542927/1332401) than for loops (as opposed to if it were a list comp). But it all depends on chunk sizes really.

> to make use of CF consistenly at any other spot, too

That's a great idea. Haven't fully explored codebase yet. Perhaps we can scope that inside another PR ?

**Comment by fhamborg** [comment]
> > removing the "inlined" for loop
> 
> Sure. Dict comprehensions (I heard comps are more pythonic, so..) are [only a couple seconds faster](https://stackoverflow.com/a/52542927/1332401) than for loops (as opposed to if it were a list comp). But it all depends on chunk sizes really.

For me it's not so much about the performance at this point but rather about readability. I think that could be improved by turning the inlined expression into a regular for loop (where the for preceeds what is done, which itself is also intended).

> Although the way I used it is already mixed up with CF in it, so I gather it wouldn't make sense to show off comps here ;)
> 
> Digressions:
> Also, I chose `exec.submit()` instead of `.map()`'ing over `urls` simultaneously since it [can't handle individual url exceptions](https://stackoverflow.com/a/51076484/1332401) in a batch, unless `.from_html` inside the loop does that (which would be a bigger fish to fry since that uses `newspaper` and hence an additional class of exceptions).

I'm not very much familiar with cf so I don't have a sound opinion on this. Regarding exceptions and your second comment: I do get your point and there's definitely some cons to it, but on the other the idea when implementing the from_urls method was that it should return as many articles' content as possible even if there was an error / exception in one or more of them. Users can then simply check the keys for whether all urls they requested are contained and take corresponding actions this way. So, I guess my question is, does the introduction of exec.submit and removal of map yield any change wrt this?
 
> > to make use of CF consistenly at any other spot, too
> 
> That's a great idea. Haven't fully explored codebase yet. Perhaps we can scope that inside another PR ?

Alright!

**Comment by arcolife** [comment]
```py
                try:
                    results[url] = future.result(timeout=timeout)
                except Exception as err:
                    results[url] = {}
```

potential for inserting exceptions right here. I personally found it easier to cope with issues in my wrapper around newsplease, when I did this: `print(err, url)`

ex:
```py
        res = NewsPlease.from_urls(feed, timeout=REQUEST_TIMEOUT)
        process_article_obj = lambda x: x.get_dict() if x else {}
        res = {k: process_article_obj(v) for k, v in res.items()}
```

So I guess it should be the user's choice to handle a url based on the exception returned. It could just be a timeout and I could pass it onto a secondary job that does it the lazy way. There's no way to interact with an exception if `{}` is returned.

**Comment by fhamborg** [comment]
In the meantime, I was using some free time to dive a bit more into this, finding that we actually already use some kind of multithreading, cf. https://github.com/fhamborg/news-please/blob/5d30d8c82416db7d4bf805aa30501266879cf780/newsplease/crawler/simple_crawler.py#L78, which is invoked by `from_urls()`. I think the PR could still be merged, e.g., if this improves the architecture/design or is more future oriented than the current implementation, but then on the other hand having some parts that use cf and other that don't seems like decreasing the consistenty throughout NP. Any thoughts on this? As said, I'm not really familiar with cf so I cannot really assess its pros and cons over what we currently have (multithreading/processing using the traditional api, which is used consistenly in np)

**Comment by fhamborg** [comment]
Regarding the exception part, see also https://github.com/fhamborg/news-please/blob/5d30d8c82416db7d4bf805aa30501266879cf780/newsplease/crawler/simple_crawler.py#L48-L72 where all/most exceptions are explicitly handled. I guess, following your argumentation, this could be a place to introduce a parameter that allows to raise rather than catch internally them.

**Comment by copperwiring** [comment]
@arcolife , @fhamborg  Is this PR still under discussion or ready to merge? Using multi core is a feature that will greatly help in downloading big chunks of data

**Comment by copperwiring** [comment]
@arcolife Does your implementation of `cf`  also allows use of multiple cores?

**Comment by fhamborg** [comment]
Ah got it! Sounds good. Feel free to open a PR regarding this or re-open this one with potentially updated code and some prior testing :-)

**Comment by arcolife** [comment]
@fhamborg let's revisit our previous discussion and let me try to clarify your doubts:

> I didn't see any advantage of using cf compared to the threading variant that we currently have, so with that in mind, I would not merge this PR. However, if there are indeed advantages, please do let me know :-)
>  finding that we actually already use some kind of multithreading, cf.

this PR isn't about multithreading, it's about multiprocessing. Perhaps that was misunderstood last time we had a chat? The advantage is - IO bound workloads are later also processed on the CPU - which is where multiprocessing comes in handy. The screenshots from issue #172 are a case in point. If you re-read that issue's description, you'll find that I'd written back then what I just tried to explain:

_"In a few runs with added debugging, I observed that the html extraction step takes a good chunk of time for completion, while the downloading part (already threaded) not so much."_

---

> im currently unsure whether we should change newsplease to make use of CF consistenly at any other spot, too, where threads/processes are currently used.

> I think the PR could still be merged, e.g., if this improves the architecture/design or is more future oriented than the current implementation, but then on the other hand having some parts that use cf and other that don't seems like decreasing the consistenty throughout NP. 

@fhamborg could you re-open this PR?  I think it's definitely towards a betterment of the library's capabilities. The PR solves multiple issues ( #169 as well )

---

> the idea when implementing the from_urls method was that it should return as many articles' content as possible even if there was an error / exception in one or more of them. Users can then simply check the keys for whether all urls they requested are contained and take corresponding actions this way. So, I guess my question is, does the introduction of exec.submit and removal of map yield any change wrt this?

this right here, the step of checking the keys in case of erroneous url processing - last I checked, wasn't straightforward. The keys using `exec.submit` in this PR introduce an empty response `{}` during exceptions - on _individual urls_ - which can be checked. 

Without it, IIRC there wasn't a way to check the URL result or for vacant result. But I'll check it once again and update the findings here. Unless you've tried it with and without this PR on your end?

**Comment by arcolife** [comment]
> I saw the code under `fetch_urls:

`fetch_urls` is IO bound. That's besides the point of "multi-core"

The actual improvement is in arranging parallel calls to `from_html` (please note, @fhamborg ) which is a CPU bound workload. And this is currently not the case.

Currently it's a simple for-loop:
```py
    @staticmethod
    def from_urls(urls, timeout=None):
 ...
        if len(urls) > 0:
            results = SimpleCrawler.fetch_urls(urls, timeout=timeout)
            for url, html in results.items():
                if html:
                    results[url] = NewsPlease.from_html(html, url, download_date)
        return results
```

While in this PR, it is a concurrent for-loop:
```py
            with cf.ProcessPoolExecutor() as exec:
                futures = {
                    exec.submit(
                        NewsPlease.from_html, results[url], url, download_date
                    ): url
                    for url in results
                }
```

---

> A good example of expected behavior i was hoping, are in the pictures in the original issue

> Does your implementation of `cf` also allows use of multiple cores? If yes, where is that parameter passed?

@copperwiring That's exactly the point of this PR - to let the multiple cores be used for extraction of HTMLs. And the reason the screenshot and the numbers in the issue made a difference.

**Comment by arcolife** [comment]
> Feel free to open a PR regarding this or re-open this one with potentially updated code and some prior testing :-)

@fhamborg To that end, there's a comment in #169 from @frankier that's about adding the same change for `from_warcs` which would be the addition I'd make after you re-open this one, if that's allowed by github (it doesn't show me the option to). Else I'll open a new PR, let me know.

As for tests, and please correct me if I'm wrong, but I didn't see any existing tests in the codebase. So that's a completely different issue.

**Comment by fhamborg** [comment]
Makes sense, thanks for the info! Unfortunately, I cannot reopen this PR, the button is disabled (a short google didn't reveal why that would be the case), so it would be great if you can create a new one (no description necessary, just insert a link to this one).

**Comment by arcolife** [comment]
Thanks @fhamborg !

I'll rebase the code and open that PR asap. 

Will also check back later to see if we can add some tests.

**Comment by arcolife** [comment]
https://github.com/fhamborg/news-please/pull/252

**Pull request closed without merging**
