### PR TITLE
Add option of replacing unicode decode errors in WARC/common crawl extraction

### PR DESCRIPTION
**Pull request by frankier**
This fixes the current exception by either explicitly replacing undecodable unicode characters or skipping those documents altogether.

### CODE REVIEW

**Comment by fhamborg** [comment]
Out of curiosity, did you experience a decoding error when using WARCs from commoncrawl? We ran these scripts multiple times for months and never had one.

**Comment by frankier** [comment]
There are yes. This is staring from March 2020 commoncrawl. They are logged
to stderr and extraction continues after the exception. It might depend
upon your logging configuration. I kept the default as discarding them and
added the option of keeping them but there is also the possibility of
ignoring only those outside the extracted content text. As to the
underlying reason there are many possibilities. In my understanding both
mixing encodings within a single document and using a different encoding
from the one declared are fairly common in the wild.

**Comment by frankier** [comment]
Rebased, and added another commit to deal with unknown encodings.

From my logs. The first exception looks like this:

```
2021-02-06 11:01:20 [newsplease.crawler.commoncrawl_extractor] ERROR: Unexpected error: <class 'UnicodeDecodeError'> ('utf-8' codec can't decode bytes in position 61838-61839: invalid continuation byte)
ERROR:newsplease.crawler.commoncrawl_extractor:<traceback object at 0x7ff81038ec88>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/newsplease/crawler/commoncrawl_extractor.py", line 250, in __process_warc_gz_file
    filter_pass, article = self.filter_record(record)
  File "/opt/coviddash/ingress/covidmarch.py", line 31, in filter_record
    passed_filters, article = super().filter_record(warc_record, article)
  File "/usr/local/lib/python3.7/dist-packages/newsplease/crawler/commoncrawl_extractor.py", line 118, in filter_record
    article = NewsPlease.from_warc(warc_record)
  File "/usr/local/lib/python3.7/dist-packages/newsplease/__init__.py", line 42, in from_warc
    html = raw_stream.decode(encoding)
```

and the second like this;

```
2021-02-06 11:01:16 [newsplease.crawler.commoncrawl_extractor] ERROR: <traceback object at 0x7ff81426cf88>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/newsplease/crawler/commoncrawl_extractor.py", line 250, in __process_warc_gz_file
    filter_pass, article = self.filter_record(record)
  File "/opt/coviddash/ingress/covidmarch.py", line 31, in filter_record
    passed_filters, article = super().filter_record(warc_record, article)
  File "/usr/local/lib/python3.7/dist-packages/newsplease/crawler/commoncrawl_extractor.py", line 118, in filter_record
    article = NewsPlease.from_warc(warc_record)
  File "/usr/local/lib/python3.7/dist-packages/newsplease/__init__.py", line 42, in from_warc
    html = raw_stream.decode(encoding)
LookupError: unknown encoding: cp-1251
```

**Comment by fhamborg** [comment]
awesome thanks a lot :)

**Pull request merged**
