### PR TITLE
Add Redis pipeline

### PR DESCRIPTION
**Pull request by anteverse**
# Add Redis / Elasticache / MemoryStore storage pipeline

Implementation choices:
* 2 collections: "CurrentVersions", and "ArchiveVersions" in order to stay to what has been done for Postgres
* For faster lookups, we use keys of that form: key = { collection name } + { separator } + { identifier }
* LZMA compression for values
* Safe to store objects not related to news-please in the same db
* Possible to set a TTL on objects stored
* Possible to disable the archive

Tests performed with a local Redis and an Elasticache Redis

### CODE REVIEW

**Comment by anteverse** [comment]
@fhamborg what's your take on this kind of pipelines? Redis caches allow a high throughput in the collection phase.
I've followed everything that's been done for Elasticsearch and Postgres but may have forgotten some entries.
Let me know if that's worth merging or not a generic case.

**Comment by fhamborg** [comment]
Yea this is great! Nothing to add :)

**Comment by anteverse** [comment]
Awesome!

**Comment by anteverse** [comment]
Any chance we can move forward and merge?

**Comment by anteverse** [comment]
Thanks!

**Pull request merged**
